"""Add source health fields

Revision ID: 35cc4675135e
Revises: ad0f290177d1
Create Date: 2026-09-22 21:14:17.635559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35cc4675135e'
down_revision: Union[str, Sequence[str], None] = 'ad0f290177d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sources', sa.Column('last_error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'last_error_message')
    op.drop_column('sources', 'last_error_at')
    op.drop_column('sources', 'last_success_at')
    # ### end Alembic commands ###
